### ISSUE TITLE
Link the documentation pages to their source on Github

### ISSUE THREAD

**Issue by ravgeetdhillon** [sharvan-sharma/CryPt-docs#2]
It would be awesome if you provide a link to the source of the documentation pages for each doc page. It would help the users to fix the typos or even add missing content to the documentation. Add a line like this at the bottom of the documentation page:

```markdown
To edit this page, kindly [view its source](github-link) on the Github.
```

**Comment by sharvan-sharma** [comment]
links are added at the bottom of each page. Thanks for suggestion

**Comment by ravgeetdhillon** [comment]
Yes. We can close the issue now.
